name: Backend Build and Push

on:
  push:
    branches:
      - dev
    paths:
      - 'src/backend/**'
      - '.github/workflows/backend-build-and-push.dev.yml'
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    outputs:
      branch_name: ${{ env.BRANCH_NAME }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get branch name
      id: branch-name
      run: |
        if [[ $GITHUB_BASE_REF ]]; then
          echo "BRANCH_NAME=$GITHUB_BASE_REF" >> $GITHUB_ENV
        else
          echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
        fi

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE_TO_ASSUME }}
        aws-region: us-east-1
        role-session-name: GitHubActionsECRPushSession

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ env.BRANCH_NAME }}-backend-repo
        IMAGE_TAG: ${{ env.BRANCH_NAME }}-${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./src/backend
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Tag image as latest for dev branch
      if: env.BRANCH_NAME == 'dev' && github.event_name == 'push'
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ env.BRANCH_NAME }}-backend-repo
        IMAGE_TAG: ${{ env.BRANCH_NAME }}-${{ github.sha }}
      run: |
        docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      BRANCH_NAME: ${{ needs.build-and-push.outputs.branch_name }}

    steps:
    - name: Update ECS service
      if: env.BRANCH_NAME == 'dev' && github.event_name == 'push'
      run: |
        aws ecs update-service \
          --cluster dev-cluster \
          --service dev-backend \
          --force-new-deployment \
          --region us-east-1

    - name: Wait for service deployment
      if: env.BRANCH_NAME == 'dev' && github.event_name == 'push'
      run: |
        aws ecs wait services-stable \
          --cluster dev-cluster \
          --services dev-backend \
          --region us-east-1

        # Verify deployment success
        DEPLOYMENT_STATUS=$(aws ecs describe-services \
          --cluster dev-cluster \
          --services dev-backend \
          --region us-east-1 \
          --query 'services[0].deployments[0].status' \
          --output text)
        
        if [ "$DEPLOYMENT_STATUS" != "PRIMARY" ]; then
          echo "Deployment failed with status: $DEPLOYMENT_STATUS"
          exit 1
        fi