name: Terraform Plan

on:
  push:
    branches:
      - main
    paths:
      - 'main/**'
  pull_request:
    branches:
      - main
    paths:
      - 'main/**'

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE_TO_ASSUME }}
        aws-region: us-east-1
        role-session-name: GitHubActionsTerraformSession

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.9.8

    - name: Terraform Init
      run: terraform init
      working-directory: ./main

    - name: Terraform Format Check
      run: terraform fmt -check
      working-directory: ./main

    - name: Terraform Plan
      run: terraform plan
      working-directory: ./main
      env:
        TF_VAR_github_token: "TEST"
        # Add any necessary environment variables for your Terraform configuration
        # For example:
        # TF_VAR_example: ${{ secrets.TF_VAR_EXAMPLE }}